name: ML Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install CPU-only version of PyTorch
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install pytest pytest-reportlog
        pip install numpy
        
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:. pytest tests/ --report-log=test_report.json -v
      
    - name: Display Model Statistics
      run: |
        echo "=== Model Performance Report ===" >> $GITHUB_STEP_SUMMARY
        echo "Test Results:" >> $GITHUB_STEP_SUMMARY
        cat test_report.json | grep -E "parameters|accuracy" >> $GITHUB_STEP_SUMMARY