name: ML Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install CPU-only version of PyTorch
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install pytest
        pip install numpy
        
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:. pytest tests/ -v 2>&1 | tee pytest_output.txt
      
    - name: Display Model Statistics
      run: |
        echo "## Model Performance Summary" >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "### Key Metrics:" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        grep -A1 "Total number of model parameters:" pytest_output.txt || true
        grep -A1 "Model accuracy after 1 epoch:" pytest_output.txt || true
        echo "```" >> $GITHUB_STEP_SUMMARY