name: ML Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install CPU-only version of PyTorch
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install pytest tqdm
        pip install numpy
        
    - name: Train Model
      run: |
        echo "Training MNIST model..."
        PYTHONPATH=$PYTHONPATH:. python -c "
        from src.train import train_model
        model, model_path = train_model(save_suffix='github')
        print(f'\nModel saved as: {model_path}')" 2>&1 | tee train_output.txt
        
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:. pytest tests/ -v 2>&1 | tee pytest_output.txt
      
    - name: Display Model Statistics
      run: |
        {
          echo "## Model Performance Summary"
          echo "---"
          echo "### Training Results:"
          echo '```'
          if [ -f train_output.txt ]; then
            grep "=== Training Summary ===" -A 2 train_output.txt || echo "No training summary found"
            grep "Model saved as:" train_output.txt || echo "No model path found"
          fi
          echo
          echo "### Model Metrics:"
          echo '```'
          if [ -f pytest_output.txt ]; then
            grep "Total number of model parameters:" pytest_output.txt || echo "No parameter count found"
            grep "Model accuracy after 1 epoch:" pytest_output.txt || echo "No accuracy found"
          fi
          echo '```'
        } >> $GITHUB_STEP_SUMMARY